language: php

matrix:
    include:
        - php: 7.3

install:
    - composer install

script:
    # test that website is generated
    - vendor/bin/statie generate source

# see docs: https://www.statie.org/docs/github-pages/
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
    local_dir: output

notifications:
    email:
        on_success: never
        on_failure: always
